simpleapp/urls.py
from django.conf.urls.static import static
from django.urls import path

from simpleapp import views
from web_repet import settings

app_name = 'simpleapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.sign_up, name='sign_up'),
    path('adauga_produs/', views.create_produs, name="adauga_produs"),
    path('search/<str:pattern>', views.EntityList.as_view(), name="search"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_repet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('simpleapp.urls')),
]

simpleapp/models.py
from django.db import models

# Create your models here.


class User(models.Model):
    username = models.CharField(max_length=30, unique=True)
    password = models.CharField(max_length=100)

    def __str__(self):
        return self.username


class Produs(models.Model):
    nume = models.CharField(max_length=100)
    descriere = models.CharField(max_length=100)
    producator = models.CharField(max_length=100)
    pret = models.IntegerField()
    cantitate = models.IntegerField()
    poza = models.ImageField(upload_to='avatars/%Y/%m/%d/', default='default.jpg')

    def __str__(self):
        return self.nume

simpleapp/forms.py
from django import forms
from django.contrib.auth.hashers import make_password

from simpleapp.models import User, Produs


class SignUpForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password')
        widgets = {
            'password': forms.PasswordInput()
        }

    def _post_clean(self):
        raw_password = self.cleaned_data['password']
        self.cleaned_data['password'] = make_password(raw_password)
        return super(SignUpForm, self)._post_clean()


class LoginForm(forms.Form):
    username = forms.CharField(max_length=30)
    password = forms.CharField(max_length=100, widget=forms.PasswordInput)


class ProdusForm(forms.ModelForm):
    class Meta:
        model = Produs
        fields = ('nume', 'descriere', 'producator', 'pret', 'cantitate', 'poza')

simpleapp/views.py
from django.contrib.auth.hashers import check_password
from django.db import connection
from django.http import HttpResponse
from django.shortcuts import render, redirect
from rest_framework.response import Response
from rest_framework.views import APIView

from simpleapp.forms import LoginForm, SignUpForm, ProdusForm
from simpleapp.models import User, Produs
from simpleapp.serializers import EntitySerializer


def sql_injection_query(user):
    with connection.cursor() as cursor:
        query = "SELECT * FROM simpleapp_user WHERE username = '%s'" % user
        cursor.execute(query)
        row = cursor.fetchone()
    return row


def index(request):
    pk = request.session.get('user_id')
    if pk:
        return redirect('simpleapp:adauga_produs')

    produse = Produs.objects.all()
    return render(request, 'index.html', {'produse': produse})


def login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            # user = User.objects.filter(username=username).first()
            user = User(*sql_injection_query(username))
            if not username:
                return HttpResponse('User-ul nu exista')

            if check_password(password, user.password):
                request.session['user_id'] = user.pk
                return redirect('simpleapp:index')
            else:
                return HttpResponse('Parola nu e corecta')
    else:
        form = LoginForm()

    return render(request, 'login.html', {'form': form})


def sign_up(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            u = User(username=username, password=password)
            u.save()

            return redirect('simpleapp:index')
    else:
        form = SignUpForm()

    return render(request, 'login.html', {'form': form})


def logout(request):
    try:
        del request.session['user_id']
    except KeyError:
        pass

    return redirect('simpleapp:index')


def create_produs(request):
    if request.method == 'POST':
        form = ProdusForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('simpleapp:index')
    else:
        form = ProdusForm()
    return render(request, 'adauga_produs.html', {
        'form': form
    })


class EntityList(APIView):
    def get(self, request, pattern):
        produse = Produs.objects.filter(nume__contains=pattern)
        serializer = EntitySerializer(produse, many=True)
        return Response(serializer.data)

simpleapp/templates/adauga_produs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Adauga produs</title>
</head>
<body>

    <a href="{% url 'simpleapp:logout' %}"> Logout </a> <br>

    Adauga produs

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>

</body>
</html>

simpleapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
</head>
<body>

<a href="{% url 'simpleapp:login' %}"> Login </a> <br>

{# jquery #}
{#<input type="text" class="search"/> <br>#}

{# js plain #}
<input type="text" class="search" onkeyup="search(this.value)"/> <br>


<div class="body" id="here">
    {% for p in produse %}
        <div class="media">
            <img class="d-flex align-self-center mr-3" width="70" height="70" src="{{ p.poza.url }}">
            <div class="media-body">
                <h5 class="mt-0" data-toggle="modal" data-target="#exampleModal{{ p.pk }}"> {{ p.nume }} </h5>
            </div>
        </div>

        <!-- Modal -->
        <div class="modal" id="exampleModal{{ p.pk }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        {{ p }}
                    </div>
                    <div class="modal-footer">
                        <img src="{{ p.poza.url }}" width="70" height="70" style="justify-content: flex-end">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>

    {% endfor %}
</div>

<script>
    {#$('.search').keyup(function () {#}
    {#    let pattern = this.value;#}
    {#    let url = '{% url 'simpleapp:search' 0 %}'.replace(0, pattern);#}
    {##}
    {#    $.ajax({#}
    {#        type: 'GET',#}
    {#        url: url,#}
    {#        success: function (result) {#}
    {#            $.each(result, function (index, element) {#}
    {#                $('.body').html('asa');#}
    {#                console.log(element.nume);#}
    {#            });#}
    {#        }#}
    {#    })#}
    {#); #}

    {#plain js#}

    function search(str) {
        let xmlhttp = new XMLHttpRequest();
        let url = '{% url 'simpleapp:search' 0 %}'.replace(0, str);


        xmlhttp.onreadystatechange = function() {
            if (this.readyState === 4 && this.status === 200) {
                {# do your job#}
                document.getElementById("here").innerHTML = this.responseText;
            }
        };

        xmlhttp.open("GET", url, true);
        xmlhttp.send();
    }

</script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
        integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
        crossorigin="anonymous"></script>
</body>
</html>

simpleapp/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Login </title>
</head>
<body>

    <h2>Login</h2>
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>

</body>
</html>